// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto_auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Session struct {
	// expiration time can be worked out client side since our jwt holds
	// the expiration time.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Session) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *Session) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type LogoutStatus struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutStatus) Reset()         { *m = LogoutStatus{} }
func (m *LogoutStatus) String() string { return proto.CompactTextString(m) }
func (*LogoutStatus) ProtoMessage()    {}
func (*LogoutStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *LogoutStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutStatus.Unmarshal(m, b)
}
func (m *LogoutStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutStatus.Marshal(b, m, deterministic)
}
func (m *LogoutStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutStatus.Merge(m, src)
}
func (m *LogoutStatus) XXX_Size() int {
	return xxx_messageInfo_LogoutStatus.Size(m)
}
func (m *LogoutStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutStatus proto.InternalMessageInfo

func (m *LogoutStatus) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LogoutStatus) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogoutStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type JWT struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (m *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(m, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidityStatus struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidityStatus) Reset()         { *m = ValidityStatus{} }
func (m *ValidityStatus) String() string { return proto.CompactTextString(m) }
func (*ValidityStatus) ProtoMessage()    {}
func (*ValidityStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *ValidityStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidityStatus.Unmarshal(m, b)
}
func (m *ValidityStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidityStatus.Marshal(b, m, deterministic)
}
func (m *ValidityStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidityStatus.Merge(m, src)
}
func (m *ValidityStatus) XXX_Size() int {
	return xxx_messageInfo_ValidityStatus.Size(m)
}
func (m *ValidityStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidityStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ValidityStatus proto.InternalMessageInfo

func (m *ValidityStatus) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Credentials)(nil), "proto.auth.Credentials")
	proto.RegisterType((*Session)(nil), "proto.auth.Session")
	proto.RegisterType((*LogoutStatus)(nil), "proto.auth.LogoutStatus")
	proto.RegisterType((*JWT)(nil), "proto.auth.JWT")
	proto.RegisterType((*ValidityStatus)(nil), "proto.auth.ValidityStatus")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x0d, 0x1f, 0x81, 0xf2, 0x0d, 0x88, 0x66, 0x25, 0xa1, 0xa9, 0x17, 0x53, 0x13, 0xe3, 0xa9,
	0x07, 0x89, 0x31, 0xf1, 0x66, 0x8c, 0x07, 0x09, 0xa7, 0x42, 0x24, 0x9e, 0xc8, 0x4a, 0x57, 0xa8,
	0x42, 0x97, 0x74, 0x66, 0x25, 0xfe, 0x6c, 0xff, 0x81, 0x99, 0xdd, 0xa2, 0x1b, 0x83, 0xa7, 0xee,
	0x7b, 0x6f, 0x66, 0x5e, 0xdf, 0x03, 0x90, 0x86, 0x96, 0xc9, 0xa6, 0xd4, 0xa4, 0x05, 0xd8, 0x4f,
	0xc2, 0x4c, 0x7c, 0x0f, 0xed, 0xbb, 0x52, 0x65, 0xaa, 0xa0, 0x5c, 0xae, 0x50, 0x44, 0xd0, 0x32,
	0xa8, 0xca, 0x42, 0xae, 0x55, 0x58, 0x3b, 0xad, 0x5d, 0xfc, 0x4f, 0xbf, 0x31, 0x6b, 0x1b, 0x89,
	0xb8, 0xd5, 0x65, 0x16, 0xfe, 0x73, 0xda, 0x0e, 0xc7, 0x4f, 0x10, 0x8c, 0x15, 0x62, 0xae, 0x0b,
	0xd1, 0x87, 0x80, 0x57, 0x66, 0x79, 0x56, 0x5d, 0x68, 0x32, 0x7c, 0xc8, 0xc4, 0x11, 0xd4, 0x5f,
	0xb7, 0x54, 0xad, 0xf2, 0x53, 0x9c, 0xc1, 0x41, 0xa9, 0x5e, 0x4a, 0x85, 0xcb, 0x19, 0xe9, 0x37,
	0x55, 0x84, 0x75, 0xab, 0x75, 0x2a, 0x72, 0xc2, 0x5c, 0x3c, 0x86, 0xce, 0x48, 0x2f, 0xb4, 0xa1,
	0x31, 0x49, 0x32, 0xf8, 0xf7, 0xfd, 0x10, 0x02, 0x34, 0xf3, 0xb9, 0x42, 0xb4, 0x1e, 0xad, 0x74,
	0x07, 0xd9, 0x79, 0x8d, 0x8b, 0xea, 0x3a, 0x3f, 0xe3, 0x13, 0xa8, 0x0f, 0xa7, 0x13, 0xd1, 0x83,
	0x86, 0x33, 0x76, 0x97, 0x1c, 0x88, 0xcf, 0xa1, 0xfb, 0x28, 0x57, 0x79, 0x96, 0xd3, 0x47, 0xe5,
	0xd9, 0x83, 0xc6, 0x3b, 0x33, 0x76, 0xae, 0x95, 0x3a, 0x70, 0xf9, 0x59, 0x83, 0xee, 0xad, 0xa1,
	0x25, 0x97, 0x37, 0x97, 0xc4, 0xe1, 0xaf, 0xa0, 0x31, 0xd2, 0x8b, 0xbc, 0x10, 0xfd, 0xe4, 0xa7,
	0xe4, 0xc4, 0x6b, 0x38, 0x3a, 0xf6, 0x85, 0x5d, 0x67, 0x03, 0x08, 0x52, 0x97, 0x59, 0xec, 0xd3,
	0xf7, 0x2f, 0xdd, 0x40, 0xdb, 0xfe, 0xa6, 0x24, 0xc5, 0x59, 0x0e, 0xfd, 0x99, 0xe1, 0x74, 0x12,
	0x45, 0x3e, 0xf1, 0x2b, 0xd0, 0x35, 0x34, 0x5d, 0xa9, 0xfb, 0xfd, 0x42, 0x9f, 0xf4, 0xdb, 0x7f,
	0x6e, 0x5a, 0x61, 0xf0, 0x15, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd8, 0x5c, 0x8f, 0x50, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Session, error)
	Refresh(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error)
	ValidateJWT(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*ValidityStatus, error)
	Logout(ctx context.Context, in *Session, opts ...grpc.CallOption) (*LogoutStatus, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/proto.auth.Authentication/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Refresh(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/proto.auth.Authentication/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) ValidateJWT(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*ValidityStatus, error) {
	out := new(ValidityStatus)
	err := c.cc.Invoke(ctx, "/proto.auth.Authentication/ValidateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) Logout(ctx context.Context, in *Session, opts ...grpc.CallOption) (*LogoutStatus, error) {
	out := new(LogoutStatus)
	err := c.cc.Invoke(ctx, "/proto.auth.Authentication/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	Login(context.Context, *Credentials) (*Session, error)
	Refresh(context.Context, *Session) (*Session, error)
	ValidateJWT(context.Context, *JWT) (*ValidityStatus, error)
	Logout(context.Context, *Session) (*LogoutStatus, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) Login(ctx context.Context, req *Credentials) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthenticationServer) Refresh(ctx context.Context, req *Session) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (*UnimplementedAuthenticationServer) ValidateJWT(ctx context.Context, req *JWT) (*ValidityStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJWT not implemented")
}
func (*UnimplementedAuthenticationServer) Logout(ctx context.Context, req *Session) (*LogoutStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.auth.Authentication/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Login(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.auth.Authentication/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Refresh(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_ValidateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).ValidateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.auth.Authentication/ValidateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).ValidateJWT(ctx, req.(*JWT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.auth.Authentication/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Logout(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.auth.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Authentication_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Authentication_Refresh_Handler,
		},
		{
			MethodName: "ValidateJWT",
			Handler:    _Authentication_ValidateJWT_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Authentication_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
