# address of the gRPC server
address: "localhost:8080"

# address of the database
repo:
    flushinterval: 3
    address: "localhost:6379"

# cipher keys used to cipher passwords
cipher:
    #    saltlength: 16
    keys:
        - "vcMGBMVbxobHRRdX1WBYq0T4L3UYWQLd"
        - "EvMT3FFDNX9dW3SggfyC7sJJ74EkzH32"
        - "tHWYreQPuHhfPLIIqcAliQWgfXdNVWLF"

# token options
token:
    refresh:
        # length of a refresh token (in characters)
        length: 32
        # expiration time of a refresh token (in hours)
        expiration: 24
    jwt:
        # expiration time of a jwt (in minutes)
        expiration: 15
