# address of the gRPC server
address: "localhost:8080"

# address of the database
repo:
    address: "localhost:6379"

# cipher keys used to cipher passwords
cipher:
    saltlength: 16
    keys:
        - "ZmRSpVCMTzFWPGfkZuhXasJJ0nTY2idd"
        - "5AWKO7URwY8927UGYrTAf9dwBIf6nTCK"
        - "tBOYjZAZ25h6n9GX6ouuehpZyyheYTNw"

# token options
token:
    refresh:
        # length of a refresh token (in characters)
        length: 32
        # expiration time of a refresh token (in hours)
        expiration: 24
    jwt:
        # expiration time of a jwt (in minutes)
        expiration: 15
